name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}  # Your private key stored in GitHub Secrets

    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@3.108.73.171 << 'EOF'
          cd /home/ec2-user/dealsdray-server
          git pull origin main
          npm install  # If your project uses Node.js (use other commands if needed for Python or other stacks)
          pm2 restart all  # If you're using PM2 for process management
        EOF
